name: Go Vet and Test

on: 
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/nehemming/*
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.20

      - name: Prepare
        run: |
          go mod tidy
          go clean --cache

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -v ./...